appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FtVSAxbRWdHVX76ikiXmRhcGysF+eIjzrtSywA6Yglp8clYsDrlVyEnhOak3ZDivZmB1cEURUxJS1hG0NRHkwIePedyc51c0bwWaEU5iLsu9fCzFfA+kcAP9ARojoKcjdVDehC9VlVI7fOEi5wdaNs4sHakSrqOkW8zH2Nvaawr+VJfi3VR9XIE4DLK/uomc6t2/rfvn17gBzueoZy5yO8SRpDC+jfvsvxT07wKwz9p+vat3D5uqh4qmt+nOxsGTQteVWwRT7iJEMOzy1vuFleAkDT4psABt9u1oPHR5HWUNr3PGZGbBtl8daAv5OjeslP6Y1YrW80uYMDxOnXKieQMc5jbKLWPrIzKzBCgzajAeBO2RhA0Vy0bj2n8sTQoLJU3m7ngRlY3a9wAhru7A5uypZlpB5th0nHen1luqZG5B0Rt7DZ4iCTYdtzsngbLSjn6TkAxKEF8EYfcoFgBsi5DAjit0+tOCJ7qpH8A8CXLtm/gxQgAjUzEHGkPl59mKi2NjygRqzPSkKT0UxcpAMaA4+qDFTchZP40ssSjl/Y16Wkh+NC25JxAYHcNJpF1No/wwuR9ovzwuyHndP9JOa29bcS/HxXGBuMXxRdM1DBMZUmT5yOU1nThnIL/DhCSv1cny1WxZhyYhjeRnqoGFhTJddHOlJ+Nc9neMBodCB2M=
